require_relative './sec_mens_bball/cli'
require_relative './sec_mens_bball/scraper'
require_relative './sec_mens_bball/team'
require_relative './sec_mens_bball/version'
require_relative './sec_mens_bball/game'